src/StayTrueService/StayTrueWebAdmin/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using DataAccessLayer;
using Microsoft.Ajax.Utilities;
using StayTrueWebAdmin.Attributes;
using StayTrueWebAdmin.Helpers;
using StayTrueWebAdmin.Interfaces;
using StayTrueWebAdmin.Models;
using StayTrueWebAdmin.Models.EditModels;
using StayTrueWebAdmin.Models.FilterModels;

namespace StayTrueWebAdmin.Controllers
{
    [ActivityLog]
    [AdminAuthorize(Roles = "administrator, superadmin")]
    public class QuizController : Controller
    {
        public IQuizzesRepository QuizzesRepository { get; set; }

        private static readonly string FolderPath = ConfigurationManager.AppSettings["VirtualDirectoryUrl"];
        // GET: Quiz

        public QuizController(IQuizzesRepository quizzesRepository)
        {
            QuizzesRepository = quizzesRepository;
        }

        public ActionResult Index(QuizzesFilterModel filter, int? page)
        {
            int pageNumber = Request.HttpMethod == "GET" ? page ?? 1 : 1;

            var games = QuizzesRepository.All;

            var filteredModel = new QuizzesFilteredModel(filter);
            filteredModel.ProcessData(games, "Id", true, pageNumber);

            filteredModel.Quizzes.ForEach(x =>
            {
                x.ImagePath = $"{FolderPath}{x.ImagePath}";
            });

            return View(filteredModel);

        }

        public ActionResult CreateQuiz()
        {
            var model = new Quizzes();
            model.PublicationDate = DateTime.Now;
            model.IsActive = false;
            return PartialView("_CreateQuiz", model);
        }



        [HttpPost]
        public ActionResult CreateQuizPost(Quizzes model, HttpPostedFileBase preview, HttpPostedFileBase quizZip)
        {
          
            if (!Request.IsAjaxRequest())
                return Json(new { success = false, message = "Запрос  напрямую. Вы че хакер?" });
            try
            {
                if (ModelState.IsValid)
                {
                    var games = QuizzesRepository.All.Where(x=>!x.IsDeleted).FirstOrDefault(x => x.Name == model.Name);
                    if (games == null)
                    {
                        model.Description = Regex.Replace(model.Description, "<.*?[^>]+>|&nbsp;", String.Empty);
                        QuizzesRepository.InsertOrUpdate(model);
                        QuizzesRepository.Save();

                        if (preview != null)
                            model.ImagePath = ImageHelper.SaveImage(preview, "Quizzes", model.Id.ToString());
                        if (quizZip != null)
                            model.Url = FileHelper.UploadZip(quizZip, "Quizzes", model.Id.ToString());
                        QuizzesRepository.Save();

                        return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                    }
                    return Json(new
                    {
                        success = false,
                        message = "Такая викторна уже существует",
                        JsonRequestBehavior.AllowGet

                    });
                }

                return Json(new
                {
                    success = false,
                    message = "Поля заполнены неверно!",
                    debug = string.Join("; ", ModelState.Values
                        .SelectMany(x => x.Errors)
                        .Select(x => x.ErrorMessage))
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    success = false,
                    message = "Ошибка выполнения программы",
                    debug = ex.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }



        public ActionResult Edit(QuizEditModel item, HttpPostedFileBase preview, HttpPostedFileBase quizZip)
        {
            if (!Request.IsAjaxRequest())
                return Json(new { success = false, message = "Запрос  напрямую. Вы че хакер?" });
            try
            {
                if (ModelState.IsValid)
                {
                    Quizzes model = QuizzesRepository.Find(item.Id);
                    if (model == null)
                    {
                        return Json(new { success = false, message = "Такой викторины не существует" });
                    }

                    model.IsActive = item.IsActive;
                    model.Name = item.Name;
                    model.PublicationDate = item.PublicationDate;
                    model.Description = item.Description;
                    model.Wincoins = item.Wincoins;

                    if (preview != null)
                    {
                        model.ImagePath = ImageHelper.SaveImage(preview, "Quizzes", item.Id.ToString());
                    }

                    if (quizZip != null)
                    {
                        FileHelper.DeleteFolder(model.Url);
                        model.Url = FileHelper.UploadZip(quizZip, "Quizzes", item.Id.ToString());
                    }

                    // item.GameUrl = FileHelper.SaveGame(quizZip, item.Id.ToString());
                    QuizzesRepository.Save();

                    return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                }

                return Json(new
                {
                    success = false,
                    message = "Поля заполнены неверно!",
                    debug = string.Join("; ", ModelState.Values
                        .SelectMany(x => x.Errors)
                        .Select(x => x.ErrorMessage))
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    success = false,
                    message = "Ошибка выполнения программы",
                    debug = ex.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult DeleteConfirmed(int id)
        {
            var game = QuizzesRepository.All.FirstOrDefault(x => x.Id == id);

            if (game == null)
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }

            QuizzesRepository.Delete(id);
            QuizzesRepository.Save();

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

    }
}

src/StayTrueService/StayTrueWebAdmin/Views/Quiz/Index.cshtml
@using System.Security.Policy
@using PagedList.Mvc
@model StayTrueWebAdmin.Models.FilterModels.QuizzesFilteredModel
@{
    ViewBag.Title = "Викторина";
}

<div class="wrap">
    @Html.Partial("_SidebarPartial")
    <div class="content">
        <div class="container-fluid">
            <div class="content-header">
                @using (Html.BeginForm("Index", "Quiz", FormMethod.Post, new { id = "FilterForm" }))
                {
                    <div class=" d-flex justify-content-center">
                        <div class="st-column">
                            <div class="filter-item-title">Дата публикации</div>
                            @Html.TextBoxFor(model => model.Filter.PublicationDateFrom, new { name = "news_published_date_min", @class = "datepicker", placeHolder = "от дд/мм/гггг" })
                            @Html.TextBoxFor(model => model.Filter.PublicationDateTo, new { name = "news_published_date_max", @class = "datepicker", placeHolder = "до дд/мм/гггг" })
                        </div>
                        <div class="st-column">
                            <div class="filter-item-title">Заголовок</div>
                            @Html.TextBoxFor(model => model.Filter.Title)
                        </div>
                        @*<div class="st-column">
                                <div class="filter-item-title">Кол-во игроков</div>
                                @Html.TextBoxFor(model => model.Filter.Players, new { placeholder = "Укажите количество" })
                            </div>*@
                        <div class="st-column">
                            <div class="filter-item-title">Кол-во Wincoin</div>
                            @Html.TextBoxFor(model => model.Filter.Wincointsfrom, new { placeholder = "Укажите количество от" })
                            @Html.TextBoxFor(model => model.Filter.Wincointsto, new { placeholder = "Укажите количество до" })
                            @*<input type="text" name="wincoin_amount" id="wincoin_amount" placeholder="Укажите количество">*@
                        </div>
                        <div class="st-column">
                            <div class="filter-item-title">Статус</div>
                            @Html.EditorFor(model => model.Filter.Status, "SearchPublicationStatus")
                        </div>
                        <div class="st-column">
                            <div class="filter-item-title"></div>
                            <button type="submit" class="st-button apply-btn border-primary bg-primary text-white">
                                <span>Применить</span>
                                <ion-icon name="ios-checkmark-circle"></ion-icon>
                            </button>
                            <button type="button" class="st-button reset-btn">
                                <span>Сбросить</span>
                                <ion-icon name="ios-close-circle"></ion-icon>
                            </button>
                        </div>
                    </div>
                }
            </div>
            <div class="content-body">
                <div id="add-quiz" class="add-new-wrap">
                    <div id="add-new-tgl">
                        <span></span>
                        <span>Добавить викторину</span>
                    </div>
                    @Html.Action("CreateQuiz")
                </div>

                @foreach (var item in Model.Quizzes)
                {
                    <div class="st-row st-game">
                        @using (Html.BeginForm("Edit", "Quiz", FormMethod.Post, new { enctype = "multipart/form-data", @class = "entity-edit" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(modelItem => item.Id)
                        <div class="st-game-header">
                            <div class="header-left">
                                <div class="st-upload game_img_upload" style="background-image: url(@item.ImagePath)">
                                    <a href="@item.ImagePath" data-fancybox></a>
                                    <label for="preview_@item.Id"></label>
                                    <input type="file" id="preview_@item.Id" accept='image/*' name="preview" class="st-upload-input user_edit_items">
                                </div>
                                <div class="game-title">
                                    @Html.TextBoxFor(modelItem => item.Name, new { @class = "game-edit-item", placeholder = "Название", disabled = "disabled" })
                                    <div class="game-zip">
                                        <span>Загрузите архив викторины:</span>
                                        <br>
                                        <input type="file" id="quizZip_@item.Id" name="quizZip" class="quiz_zip" accept=".zip">
                                    </div>
                                </div>
                            </div>
                            <div class="header-middle">
                                <div class="middle-item">
                                    <div class="item-label">Количество Wincoin:</div>
                                    @Html.TextBoxFor(modelItem => item.Wincoins, new { @class = "game-edit-item", disabled = "disabled" })
                                    @*<input type="text" value=@Html.TextBoxFor(modelItem => item.Points) class="game-edit-item" disabled>*@
                                    <div class="item-icon">
                                        <ion-icon name="ios-trophy"></ion-icon>
                                    </div>
                                </div>
                                <div class="middle-item">
                                    <div class="item-label">Показать:</div>
                                    @Html.CheckBoxFor(modelItem => item.IsActive, new { @class = "checkbox game-edit-item", @id = "item_IsActive_" + item.Id, disabled = "disabled" })
                                    @*<input type="text" value=@Html.TextBoxFor(modelItem => item.Points) class="game-edit-item" disabled>*@
                                </div>
                            </div>
                            <div class="header-right">
                                <div class="game-date">
                                    @Html.TextBoxFor(modelItem => item.PublicationDate, "{0:dd/MM/yyyy}", new { @id = "item_PublicationDate_" + item.Id, @class = "datepicker game-edit-item", disabled = "disabled", placeholder = "дд/мм/гггг" })
                                    <ion-icon name="calendar"></ion-icon>
                                </div>
                            </div>
                            <div class="quiz-description">
                                @Html.TextAreaFor(modelItem => item.Description, new { @class = "summernote"})
                            </div>
                            <div class="game-btns">
                                <div class="st-btn quiz-edit">
                                    <button type="button" class="bg-info">Редактировать</button>
                                </div>
                                <div class="st-btn" style="display: none;">
                                    <button type="button" class="delete-btn bg-danger" data-id="@item.Id" data-fancybox data-src="#delete-popup">Удалить</button>
                                </div>
                                <div class="st-btn quiz-edit-abort" style="display: none;">
                                    <button type="reset" class="bg-warning">Отменить</button>
                                </div>
                                <div class="st-btn quiz-save" style="display: none;">
                                    <button type="submit" class="bg-success">Сохранить</button>
                                </div>
                            </div>
                        </div>
                            <div class="st-game-footer">
                                <div class="game-statistics">
                                    <div class="statistics-header">
                                        <div class="st-row">
                                            <div class="st-column">
                                                <span class="column-title">Таблица лидеров</span>
                                            </div>
                                            <div class="st-column">
                                                <span class="column-title">Кол-во очков</span>
                                            </div>
                                            <div class="st-column">
                                                @*<span class="column-title">Курс Wincoin</span>
                                                    <select class="game-wincoin-currency" name="currency" disabled>
                                                        <option value="0.45">0.45</option>
                                                        <option value="0.48">0.48</option>
                                                        <option value="0.5">0.5</option>
                                                        <option value="0.55">0.55</option>
                                                    </select>*@
                                            </div>
                                        </div>
                                    </div>
                                    <div class="user-statistic">

                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                }
            </div>
            @Html.PagedListPager(Model.Quizzes, page => Url.Action("Index", new
            {
                Model.Filter.Status,
                Model.Filter.PublicationDateFrom,
                Model.Filter.PublicationDateTo,
                Model.Filter.Title,
                Model.Filter.Wincointsfrom,
                Model.Filter.Wincointsto,

                page
            }), new PagedListRenderOptions()
            {
                Display = PagedListDisplayMode.IfNeeded,
                ContainerDivClasses = new[] { "pagination" },
                UlElementClasses = new[] { "" }
            })
        </div>
    </div>
</div>

@Html.Partial("_DeleteConfirmDialogPartial")
@section Scripts {
    @Scripts.Render($"~/bundles/js/quiz-page-{BundleConfig.Version}")
}

src/StayTrueService/StayTrueWebAdmin/Views/Quiz/_CreateQuiz.cshtml
@model DataAccessLayer.Quizzes
<div class="st-row st-game" style="display: none">
    @using (Html.BeginForm("CreateQuizPost", "Quiz", FormMethod.Post, new { id = "createQuizForm", enctype = "multipart/from-data" }))
    {
    <div class="st-game-header">
        <div class="header-left">
            <div class="st-upload game_img_upload edit" style="background-image: url(/Content/img/upload-plus.png)">
                <label for="preview"></label>
                <input type="file" id="preview" accept='image/*' name="preview" class="st-upload-input user_edit_items">
            </div>
            <div class="game-title">
                @*<input type="text" class="game-edit-item" placeholder="Название игры">*@
                @Html.TextBoxFor(model => model.Name, new { @placeholder = "Название", @class = "game-edit-item" })
                <div class="game-zip">
                    <span>Загрузите архив викторины:</span>
                    <br>
                    <input type="file" id="quizZip" name="quizZip" class="quiz_zip" accept=".zip">
                </div>
            </div>
        </div>
        <div class="header-middle">
            <div class="middle-item">
                <div class="item-label">Количество Wincoin:</div>
                @*<input type="text" placeholder="0" class="game-edit-item">*@
                @Html.TextBoxFor(model => model.Wincoins, new { @placeholder = "Количество Wincoin", @class = "game-edit-item" })
                <div class="item-icon">
                    <ion-icon name="ios-trophy"></ion-icon>
                </div>
            </div>
            <div class="middle-item">
                <div class="item-label">Показать:</div>
                @Html.CheckBoxFor(model => model.IsActive, new { @class = "checkbox game-edit-item" })
                @*<input type="text" value=@Html.TextBoxFor(modelItem => item.Points) class="game-edit-item" disabled>*@
            </div>
        </div>
        <div class="header-right">
            <div class="game-date">
                @Html.TextBoxFor(model => model.PublicationDate, "{0:dd/MM/yyyy}", new { @class = "datepicker game-edit-item" })
                @*<input type="text" value="11/05/2018" class="datepicker game-edit-item" disabled>*@
                <ion-icon name="calendar"></ion-icon>
            </div>
        </div>
        <div class="quiz-description">
            @Html.TextAreaFor(model => model.Description, new { @class = "summernote" })
        </div>
        <div class="game-btns">
            <div class="st-btn quiz-add-abort">
                <button type="button">Отмена</button>
            </div>
            <div class="st-btn quiz-add">
                <button type="submit" class="bg-success">Сохранить</button>
            </div>
        </div>
    </div>
    }
</div>