src/StayTrueService/StayTrueWebAdmin/Controllers/MobileVersionController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common.Logger;
using DataAccessLayer;
using StayTrueWebAdmin.Attributes;
using StayTrueWebAdmin.Helpers;
using StayTrueWebAdmin.Interfaces;
using StayTrueWebAdmin.Models.EditModels;
using StayTrueWebAdmin.Models.FilterModels;

namespace StayTrueWebAdmin.Controllers
{
    [ActivityLog]
    [AdminAuthorize(Roles = "administrator, superadmin")]
    public class MobileVersionController : Controller
    {
        private readonly IMobileVersionRepository mobileVersionRepository;
        private static readonly string FolderUrl = ConfigurationManager.AppSettings["VirtualDirectoryUrl"];
        private static readonly string FolderPath = ConfigurationManager.AppSettings["VirtualDirectoryPath"];
        private static readonly string MobilePath = ConfigurationManager.AppSettings["MobileVersionPath"];
        private static readonly string IosUrl = ConfigurationManager.AppSettings["IosUrl"];
        private static readonly string AndroidUrl = ConfigurationManager.AppSettings["AndroidUrl"];


        public MobileVersionController(IMobileVersionRepository mobileVersionRepository)
        {
            this.mobileVersionRepository = mobileVersionRepository;
        }

        public ActionResult Index(MobileVersionFilterModel filter, int? page)
        {
            var pageNumber = Request.HttpMethod == "GET" ? page ?? 1 : 1;
            var mobileVersions = mobileVersionRepository.All;
            var filteredModel = new MobileVersionFilteredModel(filter);
            filteredModel.ProcessData(mobileVersions, "ID", true, pageNumber);

            return View(filteredModel);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(MobileVersionEditModel model)
        {
            if (ModelState.IsValid)
            {
                var lastVersion = mobileVersionRepository.All.OrderByDescending(m => m.Id).FirstOrDefault();
                if (lastVersion == null)
                    lastVersion = new MobileVersions
                    {
                        IosPath = IosUrl,
                        AndroidPath = AndroidUrl,
                        AndroidVersion = "1",
                        IosVersion = "1"
                    };
                try
                {
                    if (model.AndroidVersion == null)
                        model.AndroidVersion = lastVersion.AndroidVersion;
                    if (model.IosVersion == null)
                        model.IosVersion = lastVersion.IosVersion;
                    if (!Directory.Exists($"{MobilePath}/Backups"))
                        Directory.CreateDirectory($"{MobilePath}/Backups");
                    double folderNameNumber = FileHelper.GetDirectoryFileNameNumber();
                    FileHelper.SaveOldVersion("v"+folderNameNumber.ToString(), "STM_android_sec.apk", "stm.ipa", model);
                    if(model.AndroidBuild!=null)
                        FileHelper.UploadZip(model.AndroidBuild, MobilePath);
                    if (model.IosBuild != null)
                        FileHelper.UploadZip(model.IosBuild, MobilePath);

                    var newVersion = new MobileVersions()
                    {
                        AndroidVersion = model.AndroidVersion,
                        IosVersion = model.IosVersion,
                        AndroidPath = AndroidUrl,
                        IosPath = IosUrl
                    };
                    mobileVersionRepository.InsertOrUpdate(newVersion);
                    mobileVersionRepository.Save();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    Log.Error(ex.Message);
                     
                    return Json(new
                    {
                        success = false,
                        message = ex.Message
                    });
                }
                finally{Dispose();}
            }

            return Json(new
            {
                success = false,
                message = "Поля заполнены неверно!",
                debug = string.Join("; ", ModelState.Values
                    .SelectMany(x => x.Errors)
                    .Select(x => x.ErrorMessage))
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

src/StayTrueService/StayTrueWebAdmin/Views/MobileVersion/Create.cshtml
@using StayTrueWebAdmin.Extentions
@using PagedList.Mvc
@model  StayTrueWebAdmin.Models.EditModels.MobileVersionEditModel

@{
    ViewBag.Title = "Мобильные версии";
}

<div class="wrap">
    <div class="content brand-packs">
        <div class="container-fluid">
            <div class="content-body">
                @using (Html.BeginForm("Create", "MobileVersion", FormMethod.Post, new { @class = "add-new-pattern-form", id = "create-cigarette-brand-form", enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="st-row st-news">
                        <div class="news-top">
                            <div class="news-top-column">
                                @Html.TextBoxFor(model => model.AndroidVersion, new { @class = "news_edit_items new-title-field", placeholder="Версия Андроид"})
                            </div>
                            <div class="news-top-column">
                                @Html.TextBoxFor(model => model.IosVersion, new { @class = "news_edit_items", placeholder = "Версия IOS" })
                            </div>
                        </div>
                        <div class="news-midddle">
                            <div class="game-zip" style="display: block; margin-bottom: 10px;">
                                <span>Загрузите архив Android:</span>
                                @Html.TextBoxFor(modelItem => Model.AndroidBuild, new {type = "file", @class = "add-new-game_zip", accept = ".zip"})
                            </div>
                            <div class="game-zip" style="display: block; margin-bottom: 10px;">
                                <span>Загрузите архив IOS:</span>
                                @Html.TextBoxFor(modelItem => Model.IosBuild, new {type = "file", @class = "add-new-game_zip", accept = ".zip"})
                            </div>
                            <div class="news-middle-column">
                                <div class="brand-icon-advantages">

                                </div>
                            </div>
                        </div>
                        <div class="news-bottom">
                            <div class="btn-row row no-gutters">
                                <div class="col-4"></div>
                                <div class="col-4">
                                    <div class="center-btns btns-wrap">
                                        <div class="st-btn"><button type="button" id="create-brand-cancel">Отмена</button></div>
                                        <div class="st-btn">
                                            <button type="submit" class="bg-success border-success news-add-btn">Загрузить</button>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-4"></div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    @Html.Partial("_SidebarPartial")
</div>

<div style="display: none;" id="edit-warning" class="ban-pop-up-window">
    <form action="#" id="ban-form">
        <div class="form-inner-wrap">
            <div class="title">Сохраните или отмените редактируемые данные!</div>
        </div>
    </form>
    <div class="pop-up-message">
        <div class="title"></div>
        <div class="st-btn">
            <button data-fancybox-close class="message-btn">OK</button>
        </div>
    </div>
</div>

<div style="display: none;" id="news-delete-popup" class="ban-pop-up-window">
    <form action="#" id="ban-form">
        <div class="form-inner-wrap">
            <div class="title">Вы действительно хотите удалить версию?</div>

            <div class="st-btn">
                <button type="button" data-fancybox-close>Нет</button>
                <button type="submit">Да</button>
            </div>
        </div>
    </form>
    <div class="pop-up-message">
        <div class="title"></div>
        <div class="st-btn">
            <button data-fancybox-close class="message-btn">OK</button>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render($"~/bundles/js/mobileversion-page-{BundleConfig.Version}")
}

src/StayTrueService/StayTrueWebAdmin/Views/MobileVersion/Index.cshtml
@using StayTrueWebAdmin.Extentions
@using PagedList.Mvc
@model  StayTrueWebAdmin.Models.FilterModels.MobileVersionFilteredModel

@{
    ViewBag.Title = "Мобильные версии";
}

<div class="wrap">
    <div class="content brand-packs">
        <div class="container-fluid">
            <div class="content-header">
                @using (Html.BeginForm("Index", "MobileVersion", FormMethod.Post, new { id = "FilterForm" }))
                {
                <div class=" d-flex justify-content-center">
                    <div class="st-column">
                        <div class="filter-item-title">Версия Андроид</div>
                        @Html.TextBoxFor(model => model.Filter.AndroidVersion)
                    </div>
                    <div class="st-column">
                        <div class="filter-item-title">Версия IOS</div>
                        @Html.TextBoxFor(model => model.Filter.IosVersion)
                    </div>
                    <div class="st-column">
                        <div class="filter-item-title">Url Андроид</div>
                        @Html.TextBoxFor(model => model.Filter.AndroidPath)
                    </div>
                    <div class="st-column">
                        <div class="filter-item-title">Url IOS</div>
                        @Html.TextBoxFor(model => model.Filter.IosPath)
                    </div>
                    <div class="st-column">
                        <div class="filter-item-title"></div>
                        <button type="submit"
                                class="st-button apply-btn border-primary bg-primary text-white">
                            <span>Применить</span>
                            <ion-icon name="ios-checkmark-circle"></ion-icon>
                        </button>
                        <button type="button" class="st-button reset-btn" id="reset-filter">
                            <span>Сбросить</span>
                            <ion-icon name="ios-close-circle"></ion-icon>
                        </button>
                    </div>
                </div>
                }
            </div>
            <div class="content-body">
                <div id="create-brand" class="add-new-wrap">
                    <div id="add-new-tgl" class="news-add">
                        <span></span>
                        <span>Загрузить версию</span>
                    </div>
                </div>
                @foreach (var item in Model.MobileVersions)
                {
                    <div class="st-row st-gallery">
                        <div class="st-gallery-header">
                            @Html.HiddenFor(modelItem => item.Id)
                            <div class="header-left">
                                <div class="gallery-title">
                                    <span>Версия Андроид:</span>
                                    @Html.TextBoxFor(modelItem => item.AndroidVersion, new {disabled = "disabled"})
                                </div>
                                <div class="gallery-title">
                                    <span>Версия IOS:</span>
                                    @Html.TextBoxFor(modelItem => item.IosVersion, new {disabled = "disabled"})
                                </div>
                            </div>
                            <div class="header-right">
                                <div class="gallery-title">
                                    <span>URL IOS: @Html.DisplayFor(modelItem => item.IosPath)</span>
                                </div>
                                <div class="gallery-title">
                                    <span>URL Андроид: @Html.DisplayFor(modelItem => item.AndroidPath)</span>
                                </div>
                            </div>
                            <div class="gallery-btns">
                                <div class="st-btn">
                                    <button type="button"
                                            class="gallery-delete bg-danger border-danger"
                                            hidden>
                                        Удалить
                                    </button>
                                </div>
                                <div class="st-btn">
                                    <button type="button"
                                            class="gallery-edit-abort bg-warning border-warning"
                                            hidden>
                                        Отмена
                                    </button>
                                </div>

                            </div>
                        </div>
                    </div>
                }
            </div>
            @Html.PagedListPager(Model.MobileVersions, page => Url.Action("Index", "MobileVersion", new
            {
                Model.Filter.AndroidPath,
                Model.Filter.AndroidVersion,
                Model.Filter.IosPath,
                Model.Filter.IosVersion,

                page
            }), new PagedListRenderOptions
            {
                Display = PagedListDisplayMode.IfNeeded,
                ContainerDivClasses = new[] {"pagination"},
                UlElementClasses = new[] {""}
            })
        </div>
    </div>
    @Html.Partial("_SidebarPartial")
</div>

<div style="display: none;" id="edit-warning" class="ban-pop-up-window">
    <form action="#" id="ban-form">
        <div class="form-inner-wrap">
            <div class="title">Сохраните или отмените редактируемые данные!</div>
        </div>
    </form>
    <div class="pop-up-message">
        <div class="title"></div>
        <div class="st-btn">
            <button data-fancybox-close class="message-btn">OK</button>
        </div>
    </div>
</div>

<div style="display: none;" id="news-delete-popup" class="ban-pop-up-window">
    <form action="#" id="ban-form">
        <div class="form-inner-wrap">
            <div class="title">Вы действительно хотите удалить бренд?</div>

            <div class="st-btn">
                <button type="button" data-fancybox-close>Нет</button>
                <button type="submit">Да</button>
            </div>
        </div>
    </form>
    <div class="pop-up-message">
        <div class="title"></div>
        <div class="st-btn">
            <button data-fancybox-close class="message-btn">OK</button>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render($"~/bundles/js/mobileversion-page-{BundleConfig.Version}")
}